// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace @is.rb.payment
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class FinancialEventsKey : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"FinancialEventsKey\",\"namespace\":\"is.rb.payment\",\"fields\"" +
				":[{\"name\":\"EVENT_ID\",\"default\":0,\"type\":\"long\"}]}");
		private long _EVENT_ID;
		public virtual Schema Schema
		{
			get
			{
				return FinancialEventsKey._SCHEMA;
			}
		}
		public long EVENT_ID
		{
			get
			{
				return this._EVENT_ID;
			}
			set
			{
				this._EVENT_ID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.EVENT_ID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.EVENT_ID = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
