// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace @is.rb.payment
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class FinancialEvent : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"FinancialEvent\",\"namespace\":\"is.rb.payment\",\"fields\":[{\"" +
				"name\":\"EVENT_ID\",\"default\":0,\"type\":[\"null\",\"long\"]},{\"name\":\"DATA_OWNER\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"BANK\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"AGREEMENT_ID\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"nam" +
				"e\":\"ENTRY_DATE\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"VALUE_DATE\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"AMOUNT\",\"default\":null,\"type\":[\"" +
				"null\",\"string\"]},{\"name\":\"BALANCE\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"CURRENCY_CODE\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"LCY_AMOUNT" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"TRANSACTION_BANK\",\"default\":" +
				"null,\"type\":[\"null\",\"string\"]},{\"name\":\"TRANSACTION_CODE\",\"default\":null,\"type\":" +
				"[\"null\",\"string\"]},{\"name\":\"BATCH_NUMBER\",\"default\":null,\"type\":[\"null\",\"string\"" +
				"]},{\"name\":\"REFERENCE_NUMBER\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"" +
				"CATEGORY_CODE\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"EXTERNAL_REFERE" +
				"NCE\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"EVENT_SOURCE_CODE\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"COUNTERPARTY_ID\",\"default\":null,\"typ" +
				"e\":[\"null\",\"string\"]},{\"name\":\"VOID_CODE\",\"default\":null,\"type\":[\"null\",\"string\"" +
				"]},{\"name\":\"BOOKING_DATE\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MERC" +
				"HANT_AGREEMENT_NUMBER\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"CHEQUE_GUA" +
				"RANTEE_NUMBER\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"REFERENCE\",\"defaul" +
				"t\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"REFERENCE_DESCRIPTION\",\"default\":null" +
				",\"type\":[\"null\",\"string\"]},{\"name\":\"EXTENDED_REFERENCE\",\"default\":null,\"type\":[\"" +
				"null\",\"string\"]},{\"name\":\"COUNTERPARTY_AGREEMENT_ID\",\"default\":null,\"type\":[\"nul" +
				"l\",\"string\"]},{\"name\":\"OPERATION_REFERENCE\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"EXTERNAL_OPERATION_REFERENCE\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"ORDERER_ID\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MERC" +
				"HANT_NAME\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"OPERATION_TYPE\",\"de" +
				"fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"TELLER_ID\",\"default\":null,\"type\":" +
				"[\"null\",\"string\"]},{\"name\":\"STANDARD_DESCRIPTION\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"CHANNEL_CODE\",\"default\":null,\"type\":[\"null\",\"string\"]}]}");
		private System.Nullable<long> _EVENT_ID;
		private string _DATA_OWNER;
		private string _BANK;
		private string _AGREEMENT_ID;
		private string _ENTRY_DATE;
		private string _VALUE_DATE;
		private string _AMOUNT;
		private string _BALANCE;
		private string _CURRENCY_CODE;
		private string _LCY_AMOUNT;
		private string _TRANSACTION_BANK;
		private string _TRANSACTION_CODE;
		private string _BATCH_NUMBER;
		private string _REFERENCE_NUMBER;
		private string _CATEGORY_CODE;
		private string _EXTERNAL_REFERENCE;
		private string _EVENT_SOURCE_CODE;
		private string _COUNTERPARTY_ID;
		private string _VOID_CODE;
		private string _BOOKING_DATE;
		private System.Nullable<int> _MERCHANT_AGREEMENT_NUMBER;
		private System.Nullable<int> _CHEQUE_GUARANTEE_NUMBER;
		private string _REFERENCE;
		private string _REFERENCE_DESCRIPTION;
		private string _EXTENDED_REFERENCE;
		private string _COUNTERPARTY_AGREEMENT_ID;
		private string _OPERATION_REFERENCE;
		private string _EXTERNAL_OPERATION_REFERENCE;
		private string _ORDERER_ID;
		private string _MERCHANT_NAME;
		private string _OPERATION_TYPE;
		private string _TELLER_ID;
		private string _STANDARD_DESCRIPTION;
		private string _CHANNEL_CODE;
		public virtual Schema Schema
		{
			get
			{
				return FinancialEvent._SCHEMA;
			}
		}
		public System.Nullable<long> EVENT_ID
		{
			get
			{
				return this._EVENT_ID;
			}
			set
			{
				this._EVENT_ID = value;
			}
		}
		public string DATA_OWNER
		{
			get
			{
				return this._DATA_OWNER;
			}
			set
			{
				this._DATA_OWNER = value;
			}
		}
		public string BANK
		{
			get
			{
				return this._BANK;
			}
			set
			{
				this._BANK = value;
			}
		}
		public string AGREEMENT_ID
		{
			get
			{
				return this._AGREEMENT_ID;
			}
			set
			{
				this._AGREEMENT_ID = value;
			}
		}
		public string ENTRY_DATE
		{
			get
			{
				return this._ENTRY_DATE;
			}
			set
			{
				this._ENTRY_DATE = value;
			}
		}
		public string VALUE_DATE
		{
			get
			{
				return this._VALUE_DATE;
			}
			set
			{
				this._VALUE_DATE = value;
			}
		}
		public string AMOUNT
		{
			get
			{
				return this._AMOUNT;
			}
			set
			{
				this._AMOUNT = value;
			}
		}
		public string BALANCE
		{
			get
			{
				return this._BALANCE;
			}
			set
			{
				this._BALANCE = value;
			}
		}
		public string CURRENCY_CODE
		{
			get
			{
				return this._CURRENCY_CODE;
			}
			set
			{
				this._CURRENCY_CODE = value;
			}
		}
		public string LCY_AMOUNT
		{
			get
			{
				return this._LCY_AMOUNT;
			}
			set
			{
				this._LCY_AMOUNT = value;
			}
		}
		public string TRANSACTION_BANK
		{
			get
			{
				return this._TRANSACTION_BANK;
			}
			set
			{
				this._TRANSACTION_BANK = value;
			}
		}
		public string TRANSACTION_CODE
		{
			get
			{
				return this._TRANSACTION_CODE;
			}
			set
			{
				this._TRANSACTION_CODE = value;
			}
		}
		public string BATCH_NUMBER
		{
			get
			{
				return this._BATCH_NUMBER;
			}
			set
			{
				this._BATCH_NUMBER = value;
			}
		}
		public string REFERENCE_NUMBER
		{
			get
			{
				return this._REFERENCE_NUMBER;
			}
			set
			{
				this._REFERENCE_NUMBER = value;
			}
		}
		public string CATEGORY_CODE
		{
			get
			{
				return this._CATEGORY_CODE;
			}
			set
			{
				this._CATEGORY_CODE = value;
			}
		}
		public string EXTERNAL_REFERENCE
		{
			get
			{
				return this._EXTERNAL_REFERENCE;
			}
			set
			{
				this._EXTERNAL_REFERENCE = value;
			}
		}
		public string EVENT_SOURCE_CODE
		{
			get
			{
				return this._EVENT_SOURCE_CODE;
			}
			set
			{
				this._EVENT_SOURCE_CODE = value;
			}
		}
		public string COUNTERPARTY_ID
		{
			get
			{
				return this._COUNTERPARTY_ID;
			}
			set
			{
				this._COUNTERPARTY_ID = value;
			}
		}
		public string VOID_CODE
		{
			get
			{
				return this._VOID_CODE;
			}
			set
			{
				this._VOID_CODE = value;
			}
		}
		public string BOOKING_DATE
		{
			get
			{
				return this._BOOKING_DATE;
			}
			set
			{
				this._BOOKING_DATE = value;
			}
		}
		public System.Nullable<int> MERCHANT_AGREEMENT_NUMBER
		{
			get
			{
				return this._MERCHANT_AGREEMENT_NUMBER;
			}
			set
			{
				this._MERCHANT_AGREEMENT_NUMBER = value;
			}
		}
		public System.Nullable<int> CHEQUE_GUARANTEE_NUMBER
		{
			get
			{
				return this._CHEQUE_GUARANTEE_NUMBER;
			}
			set
			{
				this._CHEQUE_GUARANTEE_NUMBER = value;
			}
		}
		public string REFERENCE
		{
			get
			{
				return this._REFERENCE;
			}
			set
			{
				this._REFERENCE = value;
			}
		}
		public string REFERENCE_DESCRIPTION
		{
			get
			{
				return this._REFERENCE_DESCRIPTION;
			}
			set
			{
				this._REFERENCE_DESCRIPTION = value;
			}
		}
		public string EXTENDED_REFERENCE
		{
			get
			{
				return this._EXTENDED_REFERENCE;
			}
			set
			{
				this._EXTENDED_REFERENCE = value;
			}
		}
		public string COUNTERPARTY_AGREEMENT_ID
		{
			get
			{
				return this._COUNTERPARTY_AGREEMENT_ID;
			}
			set
			{
				this._COUNTERPARTY_AGREEMENT_ID = value;
			}
		}
		public string OPERATION_REFERENCE
		{
			get
			{
				return this._OPERATION_REFERENCE;
			}
			set
			{
				this._OPERATION_REFERENCE = value;
			}
		}
		public string EXTERNAL_OPERATION_REFERENCE
		{
			get
			{
				return this._EXTERNAL_OPERATION_REFERENCE;
			}
			set
			{
				this._EXTERNAL_OPERATION_REFERENCE = value;
			}
		}
		public string ORDERER_ID
		{
			get
			{
				return this._ORDERER_ID;
			}
			set
			{
				this._ORDERER_ID = value;
			}
		}
		public string MERCHANT_NAME
		{
			get
			{
				return this._MERCHANT_NAME;
			}
			set
			{
				this._MERCHANT_NAME = value;
			}
		}
		public string OPERATION_TYPE
		{
			get
			{
				return this._OPERATION_TYPE;
			}
			set
			{
				this._OPERATION_TYPE = value;
			}
		}
		public string TELLER_ID
		{
			get
			{
				return this._TELLER_ID;
			}
			set
			{
				this._TELLER_ID = value;
			}
		}
		public string STANDARD_DESCRIPTION
		{
			get
			{
				return this._STANDARD_DESCRIPTION;
			}
			set
			{
				this._STANDARD_DESCRIPTION = value;
			}
		}
		public string CHANNEL_CODE
		{
			get
			{
				return this._CHANNEL_CODE;
			}
			set
			{
				this._CHANNEL_CODE = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.EVENT_ID;
			case 1: return this.DATA_OWNER;
			case 2: return this.BANK;
			case 3: return this.AGREEMENT_ID;
			case 4: return this.ENTRY_DATE;
			case 5: return this.VALUE_DATE;
			case 6: return this.AMOUNT;
			case 7: return this.BALANCE;
			case 8: return this.CURRENCY_CODE;
			case 9: return this.LCY_AMOUNT;
			case 10: return this.TRANSACTION_BANK;
			case 11: return this.TRANSACTION_CODE;
			case 12: return this.BATCH_NUMBER;
			case 13: return this.REFERENCE_NUMBER;
			case 14: return this.CATEGORY_CODE;
			case 15: return this.EXTERNAL_REFERENCE;
			case 16: return this.EVENT_SOURCE_CODE;
			case 17: return this.COUNTERPARTY_ID;
			case 18: return this.VOID_CODE;
			case 19: return this.BOOKING_DATE;
			case 20: return this.MERCHANT_AGREEMENT_NUMBER;
			case 21: return this.CHEQUE_GUARANTEE_NUMBER;
			case 22: return this.REFERENCE;
			case 23: return this.REFERENCE_DESCRIPTION;
			case 24: return this.EXTENDED_REFERENCE;
			case 25: return this.COUNTERPARTY_AGREEMENT_ID;
			case 26: return this.OPERATION_REFERENCE;
			case 27: return this.EXTERNAL_OPERATION_REFERENCE;
			case 28: return this.ORDERER_ID;
			case 29: return this.MERCHANT_NAME;
			case 30: return this.OPERATION_TYPE;
			case 31: return this.TELLER_ID;
			case 32: return this.STANDARD_DESCRIPTION;
			case 33: return this.CHANNEL_CODE;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.EVENT_ID = (System.Nullable<long>)fieldValue; break;
			case 1: this.DATA_OWNER = (System.String)fieldValue; break;
			case 2: this.BANK = (System.String)fieldValue; break;
			case 3: this.AGREEMENT_ID = (System.String)fieldValue; break;
			case 4: this.ENTRY_DATE = (System.String)fieldValue; break;
			case 5: this.VALUE_DATE = (System.String)fieldValue; break;
			case 6: this.AMOUNT = (System.String)fieldValue; break;
			case 7: this.BALANCE = (System.String)fieldValue; break;
			case 8: this.CURRENCY_CODE = (System.String)fieldValue; break;
			case 9: this.LCY_AMOUNT = (System.String)fieldValue; break;
			case 10: this.TRANSACTION_BANK = (System.String)fieldValue; break;
			case 11: this.TRANSACTION_CODE = (System.String)fieldValue; break;
			case 12: this.BATCH_NUMBER = (System.String)fieldValue; break;
			case 13: this.REFERENCE_NUMBER = (System.String)fieldValue; break;
			case 14: this.CATEGORY_CODE = (System.String)fieldValue; break;
			case 15: this.EXTERNAL_REFERENCE = (System.String)fieldValue; break;
			case 16: this.EVENT_SOURCE_CODE = (System.String)fieldValue; break;
			case 17: this.COUNTERPARTY_ID = (System.String)fieldValue; break;
			case 18: this.VOID_CODE = (System.String)fieldValue; break;
			case 19: this.BOOKING_DATE = (System.String)fieldValue; break;
			case 20: this.MERCHANT_AGREEMENT_NUMBER = (System.Nullable<int>)fieldValue; break;
			case 21: this.CHEQUE_GUARANTEE_NUMBER = (System.Nullable<int>)fieldValue; break;
			case 22: this.REFERENCE = (System.String)fieldValue; break;
			case 23: this.REFERENCE_DESCRIPTION = (System.String)fieldValue; break;
			case 24: this.EXTENDED_REFERENCE = (System.String)fieldValue; break;
			case 25: this.COUNTERPARTY_AGREEMENT_ID = (System.String)fieldValue; break;
			case 26: this.OPERATION_REFERENCE = (System.String)fieldValue; break;
			case 27: this.EXTERNAL_OPERATION_REFERENCE = (System.String)fieldValue; break;
			case 28: this.ORDERER_ID = (System.String)fieldValue; break;
			case 29: this.MERCHANT_NAME = (System.String)fieldValue; break;
			case 30: this.OPERATION_TYPE = (System.String)fieldValue; break;
			case 31: this.TELLER_ID = (System.String)fieldValue; break;
			case 32: this.STANDARD_DESCRIPTION = (System.String)fieldValue; break;
			case 33: this.CHANNEL_CODE = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
